/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_signUp (void)
{
  GtkWidget *signUp;
  GtkWidget *fixed111;
  GtkWidget *entry_confmdp;
  GtkWidget *entry_mdp;
  GtkWidget *entry_nom;
  GtkObject *entry_age_adj;
  GtkWidget *entry_age;
  GtkWidget *entry_cin;
  GtkWidget *entry_numTel;
  GtkWidget *entry_prenom;
  GtkWidget *inscrit;
  GtkWidget *cin;
  GtkWidget *nom;
  GtkWidget *role;
  GtkWidget *age;
  GtkWidget *prenom;
  GtkWidget *sex;
  GtkWidget *numDeTel;
  GtkWidget *mdp;
  GtkWidget *confirmMpd;
  GtkWidget *region;
  GtkWidget *image1;
  GtkWidget *entry_f;
  GSList *entry_f_group = NULL;
  GtkWidget *entry_role;
  GtkWidget *entry_region;
  GtkWidget *entry_m;
  GtkWidget *button_eng1;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image12;
  GtkWidget *label39;
  GtkWidget *button_anl1;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image13;
  GtkWidget *label40;

  signUp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (signUp), _("S'inscrire"));

  fixed111 = gtk_fixed_new ();
  gtk_widget_show (fixed111);
  gtk_container_add (GTK_CONTAINER (signUp), fixed111);
  gtk_widget_set_size_request (fixed111, 461, 484);

  entry_confmdp = gtk_entry_new ();
  gtk_widget_show (entry_confmdp);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_confmdp, 120, 432);
  gtk_widget_set_size_request (entry_confmdp, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_confmdp), 8226);

  entry_mdp = gtk_entry_new ();
  gtk_widget_show (entry_mdp);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_mdp, 120, 376);
  gtk_widget_set_size_request (entry_mdp, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mdp), 8226);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_nom, 120, 80);
  gtk_widget_set_size_request (entry_nom, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_age_adj = gtk_adjustment_new (41, 0, 100, 1, 10, 10);
  entry_age = gtk_spin_button_new (GTK_ADJUSTMENT (entry_age_adj), 1, 0);
  gtk_widget_show (entry_age);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_age, 120, 272);
  gtk_widget_set_size_request (entry_age, 158, 32);

  entry_cin = gtk_entry_new ();
  gtk_widget_show (entry_cin);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_cin, 118, 217);
  gtk_widget_set_size_request (entry_cin, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin), 8226);

  entry_numTel = gtk_entry_new ();
  gtk_widget_show (entry_numTel);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_numTel, 120, 328);
  gtk_widget_set_size_request (entry_numTel, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_numTel), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_prenom, 120, 128);
  gtk_widget_set_size_request (entry_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  inscrit = gtk_label_new (_("S'inscrire"));
  gtk_widget_show (inscrit);
  gtk_fixed_put (GTK_FIXED (fixed111), inscrit, 115, 0);
  gtk_widget_set_size_request (inscrit, 128, 40);

  cin = gtk_label_new (_("CIN"));
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed111), cin, 16, 221);
  gtk_widget_set_size_request (cin, 64, 32);
  gtk_misc_set_alignment (GTK_MISC (cin), 0.5, 0.3);

  nom = gtk_label_new (_("Nom"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed111), nom, 16, 80);
  gtk_widget_set_size_request (nom, 72, 32);

  role = gtk_label_new (_("Role"));
  gtk_widget_show (role);
  gtk_fixed_put (GTK_FIXED (fixed111), role, 20, 496);
  gtk_widget_set_size_request (role, 56, 32);

  age = gtk_label_new (_("Age"));
  gtk_widget_show (age);
  gtk_fixed_put (GTK_FIXED (fixed111), age, 7, 273);
  gtk_widget_set_size_request (age, 80, 32);

  prenom = gtk_label_new (_("Prenom"));
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed111), prenom, 8, 128);
  gtk_widget_set_size_request (prenom, 90, 32);

  sex = gtk_label_new (_("Sex"));
  gtk_widget_show (sex);
  gtk_fixed_put (GTK_FIXED (fixed111), sex, 16, 176);
  gtk_widget_set_size_request (sex, 64, 32);

  numDeTel = gtk_label_new (_("     Numero \nde telephone"));
  gtk_widget_show (numDeTel);
  gtk_fixed_put (GTK_FIXED (fixed111), numDeTel, 0, 316);
  gtk_widget_set_size_request (numDeTel, 104, 56);

  mdp = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (mdp);
  gtk_fixed_put (GTK_FIXED (fixed111), mdp, 8, 380);
  gtk_widget_set_size_request (mdp, 96, 32);

  confirmMpd = gtk_label_new (_("   Confirmer \nmot de passe"));
  gtk_widget_show (confirmMpd);
  gtk_fixed_put (GTK_FIXED (fixed111), confirmMpd, 0, 424);
  gtk_widget_set_size_request (confirmMpd, 112, 48);

  region = gtk_label_new (_("Region"));
  gtk_widget_show (region);
  gtk_fixed_put (GTK_FIXED (fixed111), region, 4, 538);
  gtk_widget_set_size_request (region, 88, 40);

  image1 = create_pixmap (signUp, "2.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed111), image1, 0, 0);
  gtk_widget_set_size_request (image1, 488, 664);

  entry_f = gtk_radio_button_new_with_mnemonic (NULL, _("F"));
  gtk_widget_show (entry_f);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_f, 208, 176);
  gtk_widget_set_size_request (entry_f, 64, 32);
  gtk_container_set_border_width (GTK_CONTAINER (entry_f), 2);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (entry_f), entry_f_group);
  entry_f_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (entry_f));

  entry_role = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_role);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_role, 120, 496);
  gtk_widget_set_size_request (entry_role, 157, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role), _("-------"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_role), _("azert"));

  entry_region = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_region);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_region, 120, 546);
  gtk_widget_set_size_request (entry_region, 157, 32);

  entry_m = gtk_radio_button_new_with_mnemonic (NULL, _("M"));
  gtk_widget_show (entry_m);
  gtk_fixed_put (GTK_FIXED (fixed111), entry_m, 120, 176);
  gtk_widget_set_size_request (entry_m, 56, 32);
  gtk_container_set_border_width (GTK_CONTAINER (entry_m), 7);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (entry_m), entry_f_group);
  entry_f_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (entry_m));

  button_eng1 = gtk_button_new ();
  gtk_widget_show (button_eng1);
  gtk_fixed_put (GTK_FIXED (fixed111), button_eng1, 64, 608);
  gtk_widget_set_size_request (button_eng1, 112, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_eng1), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox7), image12, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox7), label39, FALSE, FALSE, 0);

  button_anl1 = gtk_button_new ();
  gtk_widget_show (button_anl1);
  gtk_fixed_put (GTK_FIXED (fixed111), button_anl1, 192, 609);
  gtk_widget_set_size_request (button_anl1, 96, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_anl1), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image13 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox8), image13, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox8), label40, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (signUp, signUp, "signUp");
  GLADE_HOOKUP_OBJECT (signUp, fixed111, "fixed111");
  GLADE_HOOKUP_OBJECT (signUp, entry_confmdp, "entry_confmdp");
  GLADE_HOOKUP_OBJECT (signUp, entry_mdp, "entry_mdp");
  GLADE_HOOKUP_OBJECT (signUp, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (signUp, entry_age, "entry_age");
  GLADE_HOOKUP_OBJECT (signUp, entry_cin, "entry_cin");
  GLADE_HOOKUP_OBJECT (signUp, entry_numTel, "entry_numTel");
  GLADE_HOOKUP_OBJECT (signUp, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (signUp, inscrit, "inscrit");
  GLADE_HOOKUP_OBJECT (signUp, cin, "cin");
  GLADE_HOOKUP_OBJECT (signUp, nom, "nom");
  GLADE_HOOKUP_OBJECT (signUp, role, "role");
  GLADE_HOOKUP_OBJECT (signUp, age, "age");
  GLADE_HOOKUP_OBJECT (signUp, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (signUp, sex, "sex");
  GLADE_HOOKUP_OBJECT (signUp, numDeTel, "numDeTel");
  GLADE_HOOKUP_OBJECT (signUp, mdp, "mdp");
  GLADE_HOOKUP_OBJECT (signUp, confirmMpd, "confirmMpd");
  GLADE_HOOKUP_OBJECT (signUp, region, "region");
  GLADE_HOOKUP_OBJECT (signUp, image1, "image1");
  GLADE_HOOKUP_OBJECT (signUp, entry_f, "entry_f");
  GLADE_HOOKUP_OBJECT (signUp, entry_role, "entry_role");
  GLADE_HOOKUP_OBJECT (signUp, entry_region, "entry_region");
  GLADE_HOOKUP_OBJECT (signUp, entry_m, "entry_m");
  GLADE_HOOKUP_OBJECT (signUp, button_eng1, "button_eng1");
  GLADE_HOOKUP_OBJECT (signUp, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (signUp, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (signUp, image12, "image12");
  GLADE_HOOKUP_OBJECT (signUp, label39, "label39");
  GLADE_HOOKUP_OBJECT (signUp, button_anl1, "button_anl1");
  GLADE_HOOKUP_OBJECT (signUp, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (signUp, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (signUp, image13, "image13");
  GLADE_HOOKUP_OBJECT (signUp, label40, "label40");

  return signUp;
}

GtkWidget*
create_dashboard (void)
{
  GtkWidget *dashboard;
  GtkWidget *alignment1;
  GtkWidget *eventbox1;
  GtkWidget *fixed2;
  GtkWidget *clist1;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkWidget *cin;
  GtkWidget *role;
  GtkWidget *region;
  GtkWidget *ecole;
  GtkWidget *label10;
  GtkWidget *modifier;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image15;
  GtkWidget *label42;
  GtkWidget *supprimer;
  GtkWidget *alignment12;
  GtkWidget *hbox11;
  GtkWidget *image16;
  GtkWidget *label43;
  GtkWidget *afficher;
  GtkWidget *alignment13;
  GtkWidget *hbox12;
  GtkWidget *image17;
  GtkWidget *label44;
  GtkWidget *ajouter;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image14;
  GtkWidget *label41;
  GtkWidget *prec;
  GtkWidget *alignment21;
  GtkWidget *hbox20;
  GtkWidget *image25;
  GtkWidget *label52;

  dashboard = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (dashboard), _("Gestion des utilisateurs"));

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (dashboard), alignment1);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), eventbox1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (eventbox1), fixed2);

  clist1 = gtk_clist_new (6);
  gtk_widget_show (clist1);
  gtk_fixed_put (GTK_FIXED (fixed2), clist1, 48, 48);
  gtk_widget_set_size_request (clist1, 704, 280);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 119);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 111);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 109);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 93);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 102);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 5, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  nom = gtk_label_new (_("Nom"));
  gtk_widget_show (nom);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, nom);

  prenom = gtk_label_new (_("Prenom"));
  gtk_widget_show (prenom);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, prenom);

  cin = gtk_label_new (_("CIN"));
  gtk_widget_show (cin);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, cin);

  role = gtk_label_new (_("Role"));
  gtk_widget_show (role);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, role);

  region = gtk_label_new (_("Region"));
  gtk_widget_show (region);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, region);

  ecole = gtk_label_new (_("Ecole"));
  gtk_widget_show (ecole);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 5, ecole);

  label10 = gtk_label_new (_("Gestion des utilisateurs"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 296, 0);
  gtk_widget_set_size_request (label10, 184, 40);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), modifier, 312, 368);
  gtk_widget_set_size_request (modifier, 88, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (modifier), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox10), image15, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox10), label42, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), supprimer, 416, 368);
  gtk_widget_set_size_request (supprimer, 104, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment12);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox11);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox11), image16, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox11), label43, FALSE, FALSE, 0);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed2), afficher, 552, 368);
  gtk_widget_set_size_request (afficher, 88, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (afficher), alignment13);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox12);

  image17 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox12), image17, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox12), label44, FALSE, FALSE, 0);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter, 208, 368);
  gtk_widget_set_size_request (ajouter, 88, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox9), image14, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox9), label41, FALSE, FALSE, 0);

  prec = gtk_button_new ();
  gtk_widget_show (prec);
  gtk_fixed_put (GTK_FIXED (fixed2), prec, 0, 0);
  gtk_widget_set_size_request (prec, 64, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (prec), alignment21);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox20);

  image25 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox20), image25, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Prec"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox20), label52, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dashboard, dashboard, "dashboard");
  GLADE_HOOKUP_OBJECT (dashboard, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (dashboard, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (dashboard, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (dashboard, clist1, "clist1");
  GLADE_HOOKUP_OBJECT (dashboard, nom, "nom");
  GLADE_HOOKUP_OBJECT (dashboard, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (dashboard, cin, "cin");
  GLADE_HOOKUP_OBJECT (dashboard, role, "role");
  GLADE_HOOKUP_OBJECT (dashboard, region, "region");
  GLADE_HOOKUP_OBJECT (dashboard, ecole, "ecole");
  GLADE_HOOKUP_OBJECT (dashboard, label10, "label10");
  GLADE_HOOKUP_OBJECT (dashboard, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (dashboard, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (dashboard, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (dashboard, image15, "image15");
  GLADE_HOOKUP_OBJECT (dashboard, label42, "label42");
  GLADE_HOOKUP_OBJECT (dashboard, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (dashboard, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (dashboard, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (dashboard, image16, "image16");
  GLADE_HOOKUP_OBJECT (dashboard, label43, "label43");
  GLADE_HOOKUP_OBJECT (dashboard, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (dashboard, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (dashboard, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (dashboard, image17, "image17");
  GLADE_HOOKUP_OBJECT (dashboard, label44, "label44");
  GLADE_HOOKUP_OBJECT (dashboard, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (dashboard, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (dashboard, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (dashboard, image14, "image14");
  GLADE_HOOKUP_OBJECT (dashboard, label41, "label41");
  GLADE_HOOKUP_OBJECT (dashboard, prec, "prec");
  GLADE_HOOKUP_OBJECT (dashboard, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (dashboard, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (dashboard, image25, "image25");
  GLADE_HOOKUP_OBJECT (dashboard, label52, "label52");

  return dashboard;
}

GtkWidget*
create_creation_election (void)
{
  GtkWidget *creation_election;
  GtkWidget *fixed112;
  GtkWidget *image2;
  GtkWidget *ajouter_election;
  GtkWidget *alignment14;
  GtkWidget *hbox13;
  GtkWidget *image18;
  GtkWidget *label45;
  GtkWidget *modifier_election;
  GtkWidget *alignment15;
  GtkWidget *hbox14;
  GtkWidget *image19;
  GtkWidget *label46;
  GtkWidget *supprimer_election;
  GtkWidget *alignment16;
  GtkWidget *hbox15;
  GtkWidget *image20;
  GtkWidget *label47;

  creation_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (creation_election), _("Gestion des elections"));

  fixed112 = gtk_fixed_new ();
  gtk_widget_show (fixed112);
  gtk_container_add (GTK_CONTAINER (creation_election), fixed112);

  image2 = create_pixmap (creation_election, "2.png");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed112), image2, 0, 0);
  gtk_widget_set_size_request (image2, 440, 408);

  ajouter_election = gtk_button_new ();
  gtk_widget_show (ajouter_election);
  gtk_fixed_put (GTK_FIXED (fixed112), ajouter_election, 128, 80);
  gtk_widget_set_size_request (ajouter_election, 192, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (ajouter_election), alignment14);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox13);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox13), image18, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Ajouter une election"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox13), label45, FALSE, FALSE, 0);

  modifier_election = gtk_button_new ();
  gtk_widget_show (modifier_election);
  gtk_fixed_put (GTK_FIXED (fixed112), modifier_election, 128, 184);
  gtk_widget_set_size_request (modifier_election, 192, 56);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (modifier_election), alignment15);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox14);

  image19 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox14), image19, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Modifier une election"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox14), label46, FALSE, FALSE, 0);

  supprimer_election = gtk_button_new ();
  gtk_widget_show (supprimer_election);
  gtk_fixed_put (GTK_FIXED (fixed112), supprimer_election, 128, 288);
  gtk_widget_set_size_request (supprimer_election, 192, 56);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (supprimer_election), alignment16);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox15);

  image20 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox15), image20, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Supprimer une election"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox15), label47, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (creation_election, creation_election, "creation_election");
  GLADE_HOOKUP_OBJECT (creation_election, fixed112, "fixed112");
  GLADE_HOOKUP_OBJECT (creation_election, image2, "image2");
  GLADE_HOOKUP_OBJECT (creation_election, ajouter_election, "ajouter_election");
  GLADE_HOOKUP_OBJECT (creation_election, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (creation_election, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (creation_election, image18, "image18");
  GLADE_HOOKUP_OBJECT (creation_election, label45, "label45");
  GLADE_HOOKUP_OBJECT (creation_election, modifier_election, "modifier_election");
  GLADE_HOOKUP_OBJECT (creation_election, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (creation_election, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (creation_election, image19, "image19");
  GLADE_HOOKUP_OBJECT (creation_election, label46, "label46");
  GLADE_HOOKUP_OBJECT (creation_election, supprimer_election, "supprimer_election");
  GLADE_HOOKUP_OBJECT (creation_election, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (creation_election, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (creation_election, image20, "image20");
  GLADE_HOOKUP_OBJECT (creation_election, label47, "label47");

  return creation_election;
}

GtkWidget*
create_nouvelle_election (void)
{
  GtkWidget *nouvelle_election;
  GtkWidget *fixed113;
  GtkWidget *id_election;
  GtkWidget *entry_id;
  GtkWidget *entry_date_election;
  GtkWidget *entry_nb_conseiller2;
  GtkWidget *image3;
  GtkWidget *date_election;
  GtkWidget *municipalit__;
  GtkWidget *entry_municipalite2;
  GtkWidget *entry_nb_habitant2;
  GtkWidget *nb_conseiller;
  GtkWidget *nb_habitants;
  GtkWidget *button_enregistrer3;
  GtkWidget *alignment17;
  GtkWidget *hbox16;
  GtkWidget *image21;
  GtkWidget *label48;
  GtkWidget *button_annuler3;
  GtkWidget *alignment18;
  GtkWidget *hbox17;
  GtkWidget *image22;
  GtkWidget *label49;

  nouvelle_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (nouvelle_election), _("Ajout d'election"));

  fixed113 = gtk_fixed_new ();
  gtk_widget_show (fixed113);
  gtk_container_add (GTK_CONTAINER (nouvelle_election), fixed113);

  id_election = gtk_label_new (_("Id Election"));
  gtk_widget_show (id_election);
  gtk_fixed_put (GTK_FIXED (fixed113), id_election, 0, 104);
  gtk_widget_set_size_request (id_election, 137, 41);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed113), entry_id, 128, 112);
  gtk_widget_set_size_request (entry_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_date_election = gtk_entry_new ();
  gtk_widget_show (entry_date_election);
  gtk_fixed_put (GTK_FIXED (fixed113), entry_date_election, 128, 152);
  gtk_widget_set_size_request (entry_date_election, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_date_election), 8226);

  entry_nb_conseiller2 = gtk_entry_new ();
  gtk_widget_show (entry_nb_conseiller2);
  gtk_fixed_put (GTK_FIXED (fixed113), entry_nb_conseiller2, 128, 304);
  gtk_widget_set_size_request (entry_nb_conseiller2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nb_conseiller2), 8226);

  image3 = create_pixmap (nouvelle_election, "2.png");
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed113), image3, 0, 0);
  gtk_widget_set_size_request (image3, 432, 520);

  date_election = gtk_label_new (_(" Date de \nl'election"));
  gtk_widget_show (date_election);
  gtk_fixed_put (GTK_FIXED (fixed113), date_election, 0, 144);
  gtk_widget_set_size_request (date_election, 137, 40);

  municipalit__ = gtk_label_new (_("Municipalit\303\251"));
  gtk_widget_show (municipalit__);
  gtk_fixed_put (GTK_FIXED (fixed113), municipalit__, 0, 192);
  gtk_widget_set_size_request (municipalit__, 137, 41);

  entry_municipalite2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_municipalite2);
  gtk_fixed_put (GTK_FIXED (fixed113), entry_municipalite2, 128, 192);
  gtk_widget_set_size_request (entry_municipalite2, 157, 32);

  entry_nb_habitant2 = gtk_combo_box_new_text ();
  gtk_widget_show (entry_nb_habitant2);
  gtk_fixed_put (GTK_FIXED (fixed113), entry_nb_habitant2, 128, 240);
  gtk_widget_set_size_request (entry_nb_habitant2, 156, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_nb_habitant2), _("aa"));

  nb_conseiller = gtk_label_new (_("       Nombre  \ndes conseillers"));
  gtk_widget_show (nb_conseiller);
  gtk_fixed_put (GTK_FIXED (fixed113), nb_conseiller, 0, 296);
  gtk_widget_set_size_request (nb_conseiller, 137, 41);

  nb_habitants = gtk_label_new (_("      Nombre \ndes habitants"));
  gtk_widget_show (nb_habitants);
  gtk_fixed_put (GTK_FIXED (fixed113), nb_habitants, 0, 240);
  gtk_widget_set_size_request (nb_habitants, 137, 41);

  button_enregistrer3 = gtk_button_new ();
  gtk_widget_show (button_enregistrer3);
  gtk_fixed_put (GTK_FIXED (fixed113), button_enregistrer3, 64, 368);
  gtk_widget_set_size_request (button_enregistrer3, 104, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_enregistrer3), alignment17);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox16);

  image21 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox16), image21, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox16), label48, FALSE, FALSE, 0);

  button_annuler3 = gtk_button_new ();
  gtk_widget_show (button_annuler3);
  gtk_fixed_put (GTK_FIXED (fixed113), button_annuler3, 192, 368);
  gtk_widget_set_size_request (button_annuler3, 88, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button_annuler3), alignment18);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox17);

  image22 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox17), image22, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox17), label49, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (nouvelle_election, nouvelle_election, "nouvelle_election");
  GLADE_HOOKUP_OBJECT (nouvelle_election, fixed113, "fixed113");
  GLADE_HOOKUP_OBJECT (nouvelle_election, id_election, "id_election");
  GLADE_HOOKUP_OBJECT (nouvelle_election, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (nouvelle_election, entry_date_election, "entry_date_election");
  GLADE_HOOKUP_OBJECT (nouvelle_election, entry_nb_conseiller2, "entry_nb_conseiller2");
  GLADE_HOOKUP_OBJECT (nouvelle_election, image3, "image3");
  GLADE_HOOKUP_OBJECT (nouvelle_election, date_election, "date_election");
  GLADE_HOOKUP_OBJECT (nouvelle_election, municipalit__, "municipalit__");
  GLADE_HOOKUP_OBJECT (nouvelle_election, entry_municipalite2, "entry_municipalite2");
  GLADE_HOOKUP_OBJECT (nouvelle_election, entry_nb_habitant2, "entry_nb_habitant2");
  GLADE_HOOKUP_OBJECT (nouvelle_election, nb_conseiller, "nb_conseiller");
  GLADE_HOOKUP_OBJECT (nouvelle_election, nb_habitants, "nb_habitants");
  GLADE_HOOKUP_OBJECT (nouvelle_election, button_enregistrer3, "button_enregistrer3");
  GLADE_HOOKUP_OBJECT (nouvelle_election, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (nouvelle_election, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (nouvelle_election, image21, "image21");
  GLADE_HOOKUP_OBJECT (nouvelle_election, label48, "label48");
  GLADE_HOOKUP_OBJECT (nouvelle_election, button_annuler3, "button_annuler3");
  GLADE_HOOKUP_OBJECT (nouvelle_election, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (nouvelle_election, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (nouvelle_election, image22, "image22");
  GLADE_HOOKUP_OBJECT (nouvelle_election, label49, "label49");

  return nouvelle_election;
}

GtkWidget*
create_supprimer_election (void)
{
  GtkWidget *supprimer_election;
  GtkWidget *fixed114;
  GtkWidget *image4;
  GtkWidget *entry_id_election_sup;
  GtkWidget *entry_mdp_sup;
  GtkWidget *label25;
  GtkWidget *motdepasse;
  GtkWidget *id_election_supp;
  GtkWidget *btn_eng_syp;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image10;
  GtkWidget *label37;
  GtkWidget *btn_annuler_sup;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image11;
  GtkWidget *label38;

  supprimer_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_election), _("Supprimer election"));

  fixed114 = gtk_fixed_new ();
  gtk_widget_show (fixed114);
  gtk_container_add (GTK_CONTAINER (supprimer_election), fixed114);

  image4 = create_pixmap (supprimer_election, "2.png");
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed114), image4, 0, 0);
  gtk_widget_set_size_request (image4, 304, 384);

  entry_id_election_sup = gtk_entry_new ();
  gtk_widget_show (entry_id_election_sup);
  gtk_fixed_put (GTK_FIXED (fixed114), entry_id_election_sup, 176, 88);
  gtk_widget_set_size_request (entry_id_election_sup, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_election_sup), 8226);

  entry_mdp_sup = gtk_entry_new ();
  gtk_widget_show (entry_mdp_sup);
  gtk_fixed_put (GTK_FIXED (fixed114), entry_mdp_sup, 176, 136);
  gtk_widget_set_size_request (entry_mdp_sup, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mdp_sup), 8226);

  label25 = gtk_label_new (_("Supprimer election"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed114), label25, 88, 0);
  gtk_widget_set_size_request (label25, 168, 40);

  motdepasse = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (motdepasse);
  gtk_fixed_put (GTK_FIXED (fixed114), motdepasse, 0, 133);
  gtk_widget_set_size_request (motdepasse, 169, 41);

  id_election_supp = gtk_label_new (_("Id de l'election \n  a supprimer"));
  gtk_widget_show (id_election_supp);
  gtk_fixed_put (GTK_FIXED (fixed114), id_election_supp, 0, 85);
  gtk_widget_set_size_request (id_election_supp, 169, 41);

  btn_eng_syp = gtk_button_new ();
  gtk_widget_show (btn_eng_syp);
  gtk_fixed_put (GTK_FIXED (fixed114), btn_eng_syp, 56, 224);
  gtk_widget_set_size_request (btn_eng_syp, 112, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btn_eng_syp), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox5), image10, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox5), label37, FALSE, FALSE, 0);

  btn_annuler_sup = gtk_button_new ();
  gtk_widget_show (btn_annuler_sup);
  gtk_fixed_put (GTK_FIXED (fixed114), btn_annuler_sup, 200, 224);
  gtk_widget_set_size_request (btn_annuler_sup, 104, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btn_annuler_sup), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox6), image11, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox6), label38, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_election, supprimer_election, "supprimer_election");
  GLADE_HOOKUP_OBJECT (supprimer_election, fixed114, "fixed114");
  GLADE_HOOKUP_OBJECT (supprimer_election, image4, "image4");
  GLADE_HOOKUP_OBJECT (supprimer_election, entry_id_election_sup, "entry_id_election_sup");
  GLADE_HOOKUP_OBJECT (supprimer_election, entry_mdp_sup, "entry_mdp_sup");
  GLADE_HOOKUP_OBJECT (supprimer_election, label25, "label25");
  GLADE_HOOKUP_OBJECT (supprimer_election, motdepasse, "motdepasse");
  GLADE_HOOKUP_OBJECT (supprimer_election, id_election_supp, "id_election_supp");
  GLADE_HOOKUP_OBJECT (supprimer_election, btn_eng_syp, "btn_eng_syp");
  GLADE_HOOKUP_OBJECT (supprimer_election, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (supprimer_election, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (supprimer_election, image10, "image10");
  GLADE_HOOKUP_OBJECT (supprimer_election, label37, "label37");
  GLADE_HOOKUP_OBJECT (supprimer_election, btn_annuler_sup, "btn_annuler_sup");
  GLADE_HOOKUP_OBJECT (supprimer_election, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (supprimer_election, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (supprimer_election, image11, "image11");
  GLADE_HOOKUP_OBJECT (supprimer_election, label38, "label38");

  return supprimer_election;
}

GtkWidget*
create_modifier_election (void)
{
  GtkWidget *modifier_election;
  GtkWidget *fixed115;
  GtkWidget *image5;
  GtkWidget *id_election_modifier;
  GtkWidget *municipalite;
  GtkWidget *md_nb_habitant;
  GtkWidget *md_nb_conseiller;
  GtkWidget *entry_nouv_date;
  GtkWidget *entry_munip_mdf;
  GtkWidget *entry_nbh_mdf;
  GtkWidget *entry_nbc_mdf;
  GtkWidget *nouv_date_elec;
  GtkWidget *entry_id_elec_modif;
  GtkWidget *button_conf;
  GtkWidget *alignment19;
  GtkWidget *hbox18;
  GtkWidget *image23;
  GtkWidget *label50;
  GtkWidget *button_reset;
  GtkWidget *alignment20;
  GtkWidget *hbox19;
  GtkWidget *image24;
  GtkWidget *label51;

  modifier_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_election), _("Modification"));

  fixed115 = gtk_fixed_new ();
  gtk_widget_show (fixed115);
  gtk_container_add (GTK_CONTAINER (modifier_election), fixed115);

  image5 = create_pixmap (modifier_election, "2.png");
  gtk_widget_show (image5);
  gtk_fixed_put (GTK_FIXED (fixed115), image5, 0, 0);
  gtk_widget_set_size_request (image5, 416, 496);

  id_election_modifier = gtk_label_new (_("Id election \303\240 modifier"));
  gtk_widget_show (id_election_modifier);
  gtk_fixed_put (GTK_FIXED (fixed115), id_election_modifier, 0, 72);
  gtk_widget_set_size_request (id_election_modifier, 152, 48);

  municipalite = gtk_label_new (_("Municipalite"));
  gtk_widget_show (municipalite);
  gtk_fixed_put (GTK_FIXED (fixed115), municipalite, 0, 232);
  gtk_widget_set_size_request (municipalite, 152, 48);

  md_nb_habitant = gtk_label_new (_("Modifier nombre \n      d'habitant"));
  gtk_widget_show (md_nb_habitant);
  gtk_fixed_put (GTK_FIXED (fixed115), md_nb_habitant, 0, 296);
  gtk_widget_set_size_request (md_nb_habitant, 152, 48);

  md_nb_conseiller = gtk_label_new (_("Modifier nombre\n       conseiller"));
  gtk_widget_show (md_nb_conseiller);
  gtk_fixed_put (GTK_FIXED (fixed115), md_nb_conseiller, 0, 352);
  gtk_widget_set_size_request (md_nb_conseiller, 152, 48);

  entry_nouv_date = gtk_entry_new ();
  gtk_widget_show (entry_nouv_date);
  gtk_fixed_put (GTK_FIXED (fixed115), entry_nouv_date, 176, 168);
  gtk_widget_set_size_request (entry_nouv_date, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nouv_date), 8226);

  entry_munip_mdf = gtk_entry_new ();
  gtk_widget_show (entry_munip_mdf);
  gtk_fixed_put (GTK_FIXED (fixed115), entry_munip_mdf, 176, 240);
  gtk_widget_set_size_request (entry_munip_mdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_munip_mdf), 8226);

  entry_nbh_mdf = gtk_entry_new ();
  gtk_widget_show (entry_nbh_mdf);
  gtk_fixed_put (GTK_FIXED (fixed115), entry_nbh_mdf, 176, 304);
  gtk_widget_set_size_request (entry_nbh_mdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nbh_mdf), 8226);

  entry_nbc_mdf = gtk_entry_new ();
  gtk_widget_show (entry_nbc_mdf);
  gtk_fixed_put (GTK_FIXED (fixed115), entry_nbc_mdf, 176, 360);
  gtk_widget_set_size_request (entry_nbc_mdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nbc_mdf), 8226);

  nouv_date_elec = gtk_label_new (_("Nouvelle date\n   d'election "));
  gtk_widget_show (nouv_date_elec);
  gtk_fixed_put (GTK_FIXED (fixed115), nouv_date_elec, 0, 160);
  gtk_widget_set_size_request (nouv_date_elec, 152, 48);

  entry_id_elec_modif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (entry_id_elec_modif);
  gtk_fixed_put (GTK_FIXED (fixed115), entry_id_elec_modif, 176, 80);
  gtk_widget_set_size_request (entry_id_elec_modif, 157, 32);

  button_conf = gtk_button_new ();
  gtk_widget_show (button_conf);
  gtk_fixed_put (GTK_FIXED (fixed115), button_conf, 208, 424);
  gtk_widget_set_size_request (button_conf, 96, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_conf), alignment19);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox18);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox18), image23, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox18), label50, FALSE, FALSE, 0);

  button_reset = gtk_button_new ();
  gtk_widget_show (button_reset);
  gtk_fixed_put (GTK_FIXED (fixed115), button_reset, 48, 424);
  gtk_widget_set_size_request (button_reset, 88, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button_reset), alignment20);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox19);

  image24 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox19), image24, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Reset"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox19), label51, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_election, modifier_election, "modifier_election");
  GLADE_HOOKUP_OBJECT (modifier_election, fixed115, "fixed115");
  GLADE_HOOKUP_OBJECT (modifier_election, image5, "image5");
  GLADE_HOOKUP_OBJECT (modifier_election, id_election_modifier, "id_election_modifier");
  GLADE_HOOKUP_OBJECT (modifier_election, municipalite, "municipalite");
  GLADE_HOOKUP_OBJECT (modifier_election, md_nb_habitant, "md_nb_habitant");
  GLADE_HOOKUP_OBJECT (modifier_election, md_nb_conseiller, "md_nb_conseiller");
  GLADE_HOOKUP_OBJECT (modifier_election, entry_nouv_date, "entry_nouv_date");
  GLADE_HOOKUP_OBJECT (modifier_election, entry_munip_mdf, "entry_munip_mdf");
  GLADE_HOOKUP_OBJECT (modifier_election, entry_nbh_mdf, "entry_nbh_mdf");
  GLADE_HOOKUP_OBJECT (modifier_election, entry_nbc_mdf, "entry_nbc_mdf");
  GLADE_HOOKUP_OBJECT (modifier_election, nouv_date_elec, "nouv_date_elec");
  GLADE_HOOKUP_OBJECT (modifier_election, entry_id_elec_modif, "entry_id_elec_modif");
  GLADE_HOOKUP_OBJECT (modifier_election, button_conf, "button_conf");
  GLADE_HOOKUP_OBJECT (modifier_election, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (modifier_election, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (modifier_election, image23, "image23");
  GLADE_HOOKUP_OBJECT (modifier_election, label50, "label50");
  GLADE_HOOKUP_OBJECT (modifier_election, button_reset, "button_reset");
  GLADE_HOOKUP_OBJECT (modifier_election, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (modifier_election, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (modifier_election, image24, "image24");
  GLADE_HOOKUP_OBJECT (modifier_election, label51, "label51");

  return modifier_election;
}

GtkWidget*
create_Gestion_de_reclamation (void)
{
  GtkWidget *Gestion_de_reclamation;
  GtkWidget *fixed116;
  GtkWidget *label26;
  GtkWidget *treeview1;
  GtkWidget *image29;
  GtkWidget *yz_AR;
  GtkWidget *alignment3;
  GtkWidget *hbox2;
  GtkWidget *image7;
  GtkWidget *label28;
  GtkWidget *yz_supp;
  GtkWidget *alignment5;
  GtkWidget *hbox4;
  GtkWidget *image9;
  GtkWidget *label30;
  GtkWidget *yz_modif;
  GtkWidget *alignment4;
  GtkWidget *hbox3;
  GtkWidget *image8;
  GtkWidget *label29;
  GtkWidget *yz_Prec;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image6;
  GtkWidget *label27;

  Gestion_de_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_de_reclamation), _("Gestion de reclamation"));

  fixed116 = gtk_fixed_new ();
  gtk_widget_show (fixed116);
  gtk_container_add (GTK_CONTAINER (Gestion_de_reclamation), fixed116);

  label26 = gtk_label_new (_("Gestion de reclamation"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed116), label26, 138, 0);
  gtk_widget_set_size_request (label26, 168, 40);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed116), treeview1, 16, 160);
  gtk_widget_set_size_request (treeview1, 424, 264);

  image29 = create_pixmap (Gestion_de_reclamation, "2.png");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed116), image29, 0, 0);
  gtk_widget_set_size_request (image29, 480, 592);

  yz_AR = gtk_button_new ();
  gtk_widget_show (yz_AR);
  gtk_fixed_put (GTK_FIXED (fixed116), yz_AR, 120, 56);
  gtk_widget_set_size_request (yz_AR, 208, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (yz_AR), alignment3);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox2);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox2), image7, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Ajouter reclamation"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox2), label28, FALSE, FALSE, 0);

  yz_supp = gtk_button_new ();
  gtk_widget_show (yz_supp);
  gtk_fixed_put (GTK_FIXED (fixed116), yz_supp, 120, 88);
  gtk_widget_set_size_request (yz_supp, 104, 27);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (yz_supp), alignment5);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox4);

  image9 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox4), image9, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox4), label30, FALSE, FALSE, 0);

  yz_modif = gtk_button_new ();
  gtk_widget_show (yz_modif);
  gtk_fixed_put (GTK_FIXED (fixed116), yz_modif, 232, 88);
  gtk_widget_set_size_request (yz_modif, 96, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (yz_modif), alignment4);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox3);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox3), image8, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox3), label29, FALSE, FALSE, 0);

  yz_Prec = gtk_button_new ();
  gtk_widget_show (yz_Prec);
  gtk_fixed_put (GTK_FIXED (fixed116), yz_Prec, 0, 0);
  gtk_widget_set_size_request (yz_Prec, 66, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (yz_Prec), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox1), image6, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Prec"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox1), label27, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) yz_AR, "clicked",
                    G_CALLBACK (on_yz_AR_clicked),
                    NULL);
  g_signal_connect ((gpointer) yz_supp, "clicked",
                    G_CALLBACK (on_yz_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) yz_modif, "clicked",
                    G_CALLBACK (on_yz_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) yz_Prec, "clicked",
                    G_CALLBACK (on_yz_Prec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_de_reclamation, Gestion_de_reclamation, "Gestion_de_reclamation");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, fixed116, "fixed116");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, label26, "label26");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, image29, "image29");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, yz_AR, "yz_AR");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, image7, "image7");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, label28, "label28");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, yz_supp, "yz_supp");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, image9, "image9");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, label30, "label30");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, yz_modif, "yz_modif");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, image8, "image8");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, label29, "label29");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, yz_Prec, "yz_Prec");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, image6, "image6");
  GLADE_HOOKUP_OBJECT (Gestion_de_reclamation, label27, "label27");

  return Gestion_de_reclamation;
}

GtkWidget*
create_Ajouter_reclamation (void)
{
  GtkWidget *Ajouter_reclamation;
  GtkWidget *fixed117;
  GtkWidget *yz_TR;
  GtkWidget *yz_R;
  GtkWidget *yz_id_obs;
  GtkWidget *yz_NBV;
  GtkWidget *yz_LE;
  GtkWidget *image26;
  GtkWidget *Ajouter_une_reclamation;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *button4;
  GtkWidget *alignment22;
  GtkWidget *hbox21;
  GtkWidget *image27;
  GtkWidget *label53;
  GtkWidget *annuler22;
  GtkWidget *alignment23;
  GtkWidget *hbox22;
  GtkWidget *image28;
  GtkWidget *label54;

  Ajouter_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_reclamation), _("Ajouter reclamation"));

  fixed117 = gtk_fixed_new ();
  gtk_widget_show (fixed117);
  gtk_container_add (GTK_CONTAINER (Ajouter_reclamation), fixed117);

  yz_TR = gtk_entry_new ();
  gtk_widget_show (yz_TR);
  gtk_fixed_put (GTK_FIXED (fixed117), yz_TR, 184, 216);
  gtk_widget_set_size_request (yz_TR, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (yz_TR), 8226);

  yz_R = gtk_entry_new ();
  gtk_widget_show (yz_R);
  gtk_fixed_put (GTK_FIXED (fixed117), yz_R, 136, 272);
  gtk_widget_set_size_request (yz_R, 240, 184);
  gtk_entry_set_invisible_char (GTK_ENTRY (yz_R), 8226);

  yz_id_obs = gtk_combo_box_entry_new_text ();
  gtk_widget_show (yz_id_obs);
  gtk_fixed_put (GTK_FIXED (fixed117), yz_id_obs, 184, 64);
  gtk_widget_set_size_request (yz_id_obs, 189, 29);

  yz_NBV = gtk_combo_box_entry_new_text ();
  gtk_widget_show (yz_NBV);
  gtk_fixed_put (GTK_FIXED (fixed117), yz_NBV, 184, 112);
  gtk_widget_set_size_request (yz_NBV, 189, 29);

  yz_LE = gtk_combo_box_entry_new_text ();
  gtk_widget_show (yz_LE);
  gtk_fixed_put (GTK_FIXED (fixed117), yz_LE, 184, 168);
  gtk_widget_set_size_request (yz_LE, 189, 29);

  image26 = create_pixmap (Ajouter_reclamation, "2.png");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed117), image26, 0, 0);
  gtk_widget_set_size_request (image26, 472, 624);

  Ajouter_une_reclamation = gtk_label_new (_("Ajouter une reclamation"));
  gtk_widget_show (Ajouter_une_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed117), Ajouter_une_reclamation, 104, 0);
  gtk_widget_set_size_request (Ajouter_une_reclamation, 176, 25);

  label32 = gtk_label_new (_("ID Observateur"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed117), label32, 0, 64);
  gtk_widget_set_size_request (label32, 120, 25);

  label33 = gtk_label_new (_("     Numero du \nbureau de vote "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed117), label33, 0, 109);
  gtk_widget_set_size_request (label33, 128, 40);

  label34 = gtk_label_new (_("Liste \303\251lectorale"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed117), label34, 0, 172);
  gtk_widget_set_size_request (label34, 120, 24);

  label35 = gtk_label_new (_("Type de r\303\251clamation"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed117), label35, 0, 216);
  gtk_widget_set_size_request (label35, 152, 32);

  label36 = gtk_label_new (_("R\303\251clamation"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed117), label36, 0, 264);
  gtk_widget_set_size_request (label36, 104, 48);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed117), button4, 96, 488);
  gtk_widget_set_size_request (button4, 112, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button4), alignment22);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox21);

  image27 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox21), image27, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox21), label53, FALSE, FALSE, 0);

  annuler22 = gtk_button_new ();
  gtk_widget_show (annuler22);
  gtk_fixed_put (GTK_FIXED (fixed117), annuler22, 248, 488);
  gtk_widget_set_size_request (annuler22, 88, 32);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (annuler22), alignment23);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox22);

  image28 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox22), image28, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox22), label54, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_reclamation, Ajouter_reclamation, "Ajouter_reclamation");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, fixed117, "fixed117");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, yz_TR, "yz_TR");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, yz_R, "yz_R");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, yz_id_obs, "yz_id_obs");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, yz_NBV, "yz_NBV");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, yz_LE, "yz_LE");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, image26, "image26");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, Ajouter_une_reclamation, "Ajouter_une_reclamation");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, label32, "label32");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, label33, "label33");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, label34, "label34");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, label35, "label35");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, label36, "label36");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, button4, "button4");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, image27, "image27");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, label53, "label53");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, annuler22, "annuler22");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, image28, "image28");
  GLADE_HOOKUP_OBJECT (Ajouter_reclamation, label54, "label54");

  return Ajouter_reclamation;
}

