/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_signUp (void);
GtkWidget* create_dashboard (void);
GtkWidget* create_creation_election (void);
GtkWidget* create_nouvelle_election (void);
GtkWidget* create_supprimer_election (void);
GtkWidget* create_modifier_election (void);
GtkWidget* create_Gestion_de_reclamation (void);
GtkWidget* create_Ajouter_reclamation (void);
